version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: quanminh
      MONGO_INITDB_ROOT_PASSWORD: minhquan
      MONGODB_DB: Charles_learn
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
