import type { Metadata } from "next";
import "./globals.css";
import ButtonDarkMode from "../ui/button-dark-mode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto text-center p-5 min-h-screen bg-white text-black dark:bg-black dark:text-white transition-colors">
          {children}
          <ButtonDarkMode />
        </div>
      </body>
    </html>
  );
}
